GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2VzZXRodTI0IiwiaWF0IjoxNjUxMjQwNzQ5fQ.owqDg3fvUEbbXWcu92rWEA3Zs98Kos5JA3FgYBvfLuw

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "username" :"Sesethu24"
}
